all:
	p4c --target bmv2 --arch v1model --std p4-16 4client.p4
	mv 4client.json ~/Hangar/build/BMv2/networks/4client
clean:
	rm -rf ~/Hangar/build/BMv2/networks/4client/4client.json
	rm -rf ~/Hangar/networks/4client/4client.json
